# Generated by Django 3.2.10 on 2022-01-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_alter_carona_passageiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avaliacao',
            field=models.FloatField(default=5.0),
        ),
    ]
