# Generated by Django 3.2.10 on 2022-02-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0007_auto_20220127_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='dias',
            field=models.IntegerField(),
        ),
    ]
