# Generated by Django 3.2.10 on 2022-02-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0009_auto_20220201_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='enderecoDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.endereco'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='enderecoSaida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecoSaida', to='carpool.endereco'),
        ),
    ]
