# Generated by Django 3.2.10 on 2022-03-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0010_auto_20220207_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='carro',
            new_name='temCarro',
        ),
        migrations.RemoveField(
            model_name='mensagemusuarios',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mensagemcarona',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='carpool.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagemusuarios',
            name='carona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carpool.carona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagemusuarios',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinatario', to='carpool.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagemusuarios',
            name='remetente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='remetente', to='carpool.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
