# Generated by Django 3.2.10 on 2022-03-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpool', '0012_auto_20220310_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='conta',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='perfil', to='auth.user'),
            preserve_default=False,
        ),
    ]
